language: cpp
compiler: clang


before_script:
  - sudo apt-get install libboost-test-dev -y
  - echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get install doxygen
  - sudo apt-get install graphviz
script:
  - doxygen ./Doxyfile
  - cmake .
  - cmake --build .
deploy:
  - provider: pages
    skip_cleanup: true
    github-token: $GITHUB_TOKEN 
    keep-history: false
    local-dir: doxygen/html/
    on:
      branch: master
